POST  http://localhost:4131/JSONAdminApi/AdminApi/Reports/ledgerAutoJsonFile/Utilities/import
content-type: application/json

  {
    "ToName": "Purchases1",
    "ReportConficObject": {
        "VouchersConsider": "hhhh"
    }
}
