GET   http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/UserFile/ItemName/ScreenName/CreateNew/CreateScreen
content-type: application/json

{
  
 "FolderName": "",
    "FileName": "",
    "ItemName": "",
    "ScreenName": ""
}