POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/UserFile/ItemName/ScreenName/CreateNew/CreateScreen
Cookie:KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IkpBVElOIiwiRGF0YVBrIjoyMDAyLCJpYXQiOjE2ODU3OTUxMjF9.yn_qvnV1SURkSiXcaXSaxOt0dy6KY3z9BqeN8Y_xe38
content-type: application/json

{
  

}