PATCH http://localhost:4119/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigFolder/Duplicate/DuplicateFolder
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IkRVUkdBUEtMMjIyMyIsIkRhdGFQayI6MTAyMiwiaWF0IjoxNjgyNDAzODM3fQ.hyek57NF8MWfjQNo3ZjaDcJIfaRS16if7DIne7pW0Jo
content-type: application/json

{
}