POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/UserFile/ItemName/ScreenName/CreateNew/CreateScreen
content-type: application/json

{
  
 "FolderName": "Masters",
    "FileName": "Items",
    "ItemName": "ItemNames",
    "NewScreenName": "Create"
}