POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/UserFile/ItemName/ScreenName/CreateNew/CreateScreen
content-type: application/json

{
  
 "FolderName": "Transactions",
    "FileName": "All",
    "ItemName": "ACCOUNT-OPENINGS",
    "NewScreenName": "Create"
}