GET http://localhost:4119/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ScreensFromDisplayJson/SubTableColumns/SubKeys/HtmlAttributes
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IktJUkFOQTIxIiwiRGF0YVBrIjoyMCwiaWF0IjoxNjg1NTE3MTAzfQ.yrgJI81a2eYPPAjVWlmQBYLcGYsd1_vglnaN-q_FDcU
content-type: application/json

{
  
}