PATCH http://localhost:4119/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ScreensFromDisplayJson/SubTableColumns/SubKeys/HtmlAttributes
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IktJUkFOQSIsIkRhdGFQayI6MjAsImlhdCI6MTY4NTUxOTU4NX0.V6z0lVNSFIki3ppSDYMVDr9DcPYScF1Vw5L6kc0bris
content-type: application/json

{
    "folderName": "Sales",
    "FileName": "Sale",
    "ItemName": "Create",
    "ScreenName": "InvGrid",
    "DataAttribute": "ItemName",
    "BodyAsJson": {
        "KTF": true,
        "list": "String"
    }
}
  
