PATCH  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/DataFolder/FileinFolder/Duplicate/DuplicateFile
content-type: application/json

{"folderName": "Transactions", "inFileNameOnly": "MVP", "inToFileName": "kkk"}