POST  http://localhost:4119/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/DataFolder/FileInFolder/ItemName/InsertNew/InsertNew
content-type: application/json

{
     "FolderName": "Masters",
    "FileName": "Items"
}