POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/DataFolder/FileInFolder/CreateNew/CreateFile
content-type: application/json

{
  "FolderName": "Transactions",
    "NewFileName": "Sales"
}