PATCH  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ScreensFromDisplayJson/SubTableInfo/SubMenu/TableRowOptions/Edit
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IksyNSIsIkRhdGFQayI6MSwiaWF0IjoxNjg3MzM0NTIzfQ.nDF6VbD3_rtwA3DmoadXEZGcMbc7E4F1tm0ueVAObhI
content-type: application/json

{
   "FolderName": "Transactions",
    "FileName": "GST-SALES",
    "ItemName": "GST-SALE",
    "ScreenName": "Create",
    "GridName": "InvGrid",
    "BodyAsJson": {"SubTableRowEdit":true}
}
  
