POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/UserFile/ItemName/ScreenName/TableColumns/CreateNew/CreateColumn
content-type: application/json

{
   "FolderName": "Fold3",
    "FileName": "File3",
    "ItemName": "Item3",
    "ScreenName": "Create"
 
}