POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/UserFile/ItemName/ScreenName/TableColumns/CreateNew/CreateColumn
content-type: application/json

{
   "FolderName": "Folder8",
    "FileName": "File8",
    "ItemName": "Item8",
    "ScreenName": "Create",
     "NewColumnName": "ItemName"
 
}