POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigFolder/UserFileAsFolder/JsonItem/JsonScreen/TableColumns/CreateNew/CreateColumn
content-type: application/json

{
   
"FolderName": "Transactions",
    "FileName": "GST-SALES",
    "ItemName": "GST-SALE",
    "ScreenName": "Create",
    "NewColumnName": "sreeeee"
  
 
}