DELETE  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/CreateNew/CreateFolder
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IkZBUSIsIkRhdGFQayI6MTksImlhdCI6MTY4NTgwMTUxNX0.BZKKECfC3t-SkDAUwLd3dUdkhXE7qRUUF2Bkg3eTUW4
content-type: application/json

{
     "NewFolderName":"Fold3"
}