POST  http://localhost:4131/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ConfigAndDataFolders/CreateNew/CreateFolder
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IkZBUSIsIkRhdGFQayI6MTksImlhdCI6MTY4NjAyODU4MX0.f2R83eJ64F8V0MZjSGS9VK1BqclQwvFXTEExL96Sd7Y
content-type: application/json

{
    "NewFolderName": "Folder8"
}