PATCH http://localhost:4119/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ScreensFromDisplayJson/TableColumns/SubKeys/ClientEval
content-type: application/json

{
    "folderName": "CRM",
    "FileName": "Customers",
    "ItemName": "CustomerDetails",
    "ScreenName": "Create",
    "DataAttribute": "pk",
    "BodyAsJson": {
        "ClientEval": "ssss"
    }
}